- hosts: all
  vars:
    unit_name: isuride-go
    binary_name: isuride
  tasks:
    - name: chown /home/isucon
      shell: "chown -R {{ ansible_ssh_user }} /home/isucon"
      become: True
    - name: sync webapp
      synchronize:
        src: ./webapp
        dest: /home/isucon
    - name: sync env.sh
      synchronize:
        src: ./env.sh
        dest: /home/isucon/env.sh
    - name: build
      shell: |
        cd /home/isucon/webapp/go
        /home/isucon/local/golang/bin/go build -o {{ binary_name }}
      become_user: isucon

    - name: restart webapp
      shell: |
        systemctl restart {{ unit_name }}
      become: True
